Rails:
  Enabled: true

# Can non-ascii comments.
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
# Limit lines to 80 characters.
Style/LineLength:
  Enabled: false
# Warn Hoge::Fuge
Style/ClassAndModuleChildren:
  Enabled: false
