AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

# Limit lines to 80 characters.
Metrics/LineLength:
  Enabled: false
# Can non-ascii comments.
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
# Warn Hoge::Fuge
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/IndentationConsistency:
  SupportedStyles: rails
