# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f5b576950cae70c4e5db0e6eebc738108464e3849ead4b486856afd173d341a3bb2644d0eeaaace452acec269706bd8bd1b0fba43578d36e71971a72627b1e9

test:
  secret_key_base: 7088f56728091dce9bb1e95e1581503093c0204d2999459b89a73fe61d14ffd8958972422c4fa20329bdb9e7903b608b6f487503d549492ba8b61bbe286aa9af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
